import { ArrowRight, Clock3, MapPin, ShieldCheck, Thermometer } from 'lucide-react'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { categoryLabels, remainingLabel, statusLabels, type Donation, type PilotData } from '@/src/types'

export function DonationDialog({ donation, data, now, close }: { donation: Donation | null; data?: PilotData; now: number; close: () => void }) {
  const donor = data?.donors.find(d => d.id === donation?.donor_id)
  const recipient = data?.recipients.find(r => r.id === donation?.recipient_id)
  const driver = data?.drivers.find(d => d.id === donation?.driver_id)
  return <Dialog open={!!donation} onOpenChange={open => { if (!open) close() }}><DialogContent className="sm:max-w-lg p-6"><DialogHeader><DialogTitle>{donation?.item ?? 'Rescue details'}</DialogTitle><DialogDescription>{donor?.name} · {donation?.is_synthetic ? 'Synthetic pilot donation' : 'Donation details'}</DialogDescription></DialogHeader>{donation && <><div className="flex flex-wrap gap-2"><Badge variant="secondary">{statusLabels[donation.status]}</Badge><Badge variant="outline">{categoryLabels[donation.category]}</Badge></div><div className="donation-detail-grid"><div><span>Available quantity</span><strong>{donation.qty_kg} kg</strong></div><div><span><Clock3 size={13} />Safe window</span><strong>{remainingLabel(donation.safe_until, now)}</strong></div><div><span><Thermometer size={13} />Attested temperature</span><strong>{donation.temp_c === null ? 'Not applicable' : `${donation.temp_c} °C`}</strong></div><div><span><MapPin size={13} />Pickup area</span><strong>{donor?.area ?? 'Not recorded'}</strong></div></div>{recipient && <div className="detail-safety"><ShieldCheck size={17} /><p>Destination: <strong>{recipient.name}</strong><span className="unit"> · {recipient.area}</span></p></div>}{driver && <p className="flex items-center gap-1.5 text-xs text-muted-foreground">Assigned driver: <strong>{driver.name}</strong><span className="unit"> · {driver.vehicle}</span></p>}<div className="detail-safety"><ShieldCheck size={17} /><p>Consume by <strong>{new Date(donation.safe_until).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', dateStyle: 'medium', timeStyle: 'short' })} IST</strong>. This is a coordination cutoff, not a food-safety certification.</p></div><p className="text-xs text-muted-foreground">FSSAI license: {donor?.license_no ? 'Collected, not verified' : 'Not supplied'}. Prepared {new Date(donation.prepared_at).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST.</p></>}</DialogContent></Dialog>
}
