import { ArrowUpRight, Bike, CheckCheck, HeartHandshake, MapPin, ShieldCheck, Users } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from '@/components/ui/empty'
import { categoryLabels, number, type PilotData } from '@/src/types'

function NetworkEmpty({ type }: { type: string }) {
  return <Empty className="min-h-72"><EmptyHeader><EmptyMedia variant="icon"><Users /></EmptyMedia><EmptyTitle>{type} will appear here</EmptyTitle><EmptyDescription>The synthetic Bengaluru network will be available once the database migration and seed are approved.</EmptyDescription></EmptyHeader></Empty>
}
export function RecipientView({ data }: { data?: PilotData }) {
  return <section><div className="section-intro"><ShieldCheck size={17} /><span>Only approved, open recipients with available capacity are eligible for matching.</span></div><div className="network-grid">{data?.recipients.map(r => <article className="panel network-card" key={r.id}><div className="flex justify-between items-start"><span className="network-card-icon"><HeartHandshake size={23} /></span><Badge variant={r.approved && r.is_open ? 'secondary' : 'outline'}>{r.approved ? r.is_open ? 'Ready to receive' : 'Closed' : 'Approval pending'}</Badge></div><h2>{r.name}</h2><p className="location-line"><MapPin size={13} />{r.area}, Bengaluru</p><div className="capacity-line"><span>Available capacity</span><strong>{number(Math.max(0, r.capacity_kg - r.reserved_kg))} <small>/ {number(r.capacity_kg)} kg</small></strong></div><progress className="capacity-progress" value={r.reserved_kg} max={r.capacity_kg} aria-label={`Reserved capacity at ${r.name}`} /><div className="flex gap-1.5 flex-wrap mt-4">{r.accepts.map(c => <Badge key={c} variant="outline">{categoryLabels[c]}</Badge>)}</div><div className="network-card-footer"><span><CheckCheck size={14} />{r.approved ? 'Coordinator approved' : 'Awaiting review'}</span><span>Synthetic</span></div></article>)}</div>{!data?.recipients.length && <div className="panel"><NetworkEmpty type="Recipient organizations" /></div>}</section>
}
export function DriverView({ data, onDispatch }: { data?: PilotData; onDispatch: () => void }) {
  return <section><div className="section-intro"><Bike size={17} /><span>Availability reflects stored records, not live GPS. Contact details are never shown publicly.</span></div><div className="network-grid">{data?.drivers.map(d => <article className="panel network-card" key={d.id}><div className="flex justify-between"><span className="driver-avatar">{d.name.split(' ').slice(0, 2).map(word => word[0]).join('')}</span><Badge variant={d.availability ? 'secondary' : 'outline'}>{d.availability ? 'Available' : 'On a rescue'}</Badge></div><h2>{d.name}</h2><p className="location-line"><Bike size={14} />{d.vehicle} · up to {number(d.capacity_kg)} kg</p><div className="driver-footer"><span>Synthetic volunteer</span><Button variant="outline" size="sm" onClick={onDispatch}>View dispatch<ArrowUpRight data-icon="inline-end" /></Button></div></article>)}</div>{!data?.drivers.length && <div className="panel"><NetworkEmpty type="Volunteer drivers" /></div>}</section>
}
